### ISSUE TITLE
better browse for folder

### ISSUE THREAD

**Issue by MaxSteven** [arnobpl/SymlinkCreator#9] opened 2023-07-17 10:56 UTC
First of all 
Thank you for create this useful tool
I only have one suggestion that a better browser window.
Current browser doesnt allow to paste path which faster to create

And maybe a drag folder/file to the folder/file source list could be really helpful

Thank you for reading this

**Comment by arnobpl** [comment] 2023-07-19 17:45
Thank you for using Symlink Creator Glad to know that you have found it useful. :)

There is drag-n-drop feature already existed in the current version of Symlink Creator so that you don't need to copy/paste file/folder paths. Make sure that you are NOT running Symlink Creator as administrator.

**Comment by arnobpl** [comment] 2023-09-22 03:40
Duplicate of #10

**Comment by arnobpl** [comment] 2023-09-22 03:41
Closing this issue in favor of the similar issue #10  which has a better description.

**Closed by arnobpl** 2023-09-22 03:41 UTC
Labels: enhancement, good first issue
