### ISSUE TITLE
Symlink script returned with an error

### ISSUE THREAD

**Issue by comejv** [arnobpl/SymlinkCreator#15] opened 2024-02-08 17:30 UTC
Hello,
I was trying to find an app/script that'd let me move unused apps/folders to my HDD when I found your repo. Tried using the release 1.2.5 but when moving anything I get a "Simlink script return with an error" :
![Screenshot of the error](https://github.com/arnobpl/SymlinkCreator/assets/44554692/767110e5-1801-43c4-9eae-81d63da06066)
(in the screenshot tried moving the app itself but tried with other things too)

I tried moving a folder and a file, tried moving to same drive or different drive, running as administrator. Any idea what it could be ?
Windows 11 Pro 23H2

Thanks for your help,
Côme

**Comment by arnobpl** [comment] 2024-02-11 20:54
Hi Côme,

First of all, thank you for using Symlink Creator and reaching out to me
about this issue. Could you tell me what is your file system of your
destination path (D:\)? I suspect, your destination file system is not
supported for symlink. If that is not the case, then I suspect, it is
blocked by your computer's policy. You can check that by running the
following command (needs admin rights):

fsutil behavior set symlinkevaluation /?
>

The output of the command shows if symlink creation permission is enabled
for different cases (local-to-local, local-to-remote, remote-to-local,
remote-to-remote).

Let me know if it helps.

Happy symlinking! :)

Best,
Arnob Paul

**Comment by arnobpl** [comment] 2024-02-19 15:57
I have reopened the issue. I will take a look to understand what might get wrong.

**Comment by arnobpl** [comment] 2024-02-20 02:24
Welcome. One thing I would like to know about the exit code coming from the script. To do so:
1. In the application, tick "Retain script file after execution".
2. Add a source file and set a destination path. It could be anything. I just want to test why it never worked.
3. Click "Create symlinks" button and grant admin permission.
4. So it will fail in your system. Now go to the Symlink Creator application's path and find the script file, say `SymlinkCreator_1234567890.cmd`. 
5. Copy `SymlinkCreator_1234567890.cmd` file to Downloads folder.
6. Right-click Start Button on Taskbar and click "Terminal (Admin)".
7. Now copy-paste the following command (and replace `SymlinkCreator_1234567890.cmd` with the actual script filename) in terminal, and click "Paste anyway" button in the warning dialog and press Enter:
```
cd .\Downloads
.\SymlinkCreator_1234567890.cmd
echo $LASTEXITCODE

```
8. Terminal will print a number at the end. Let me know what is the number. Is it just `1` or something else? Also, do you see any other error messages in the terminal?

Hope that will find something in your system. Then we can proceed further to solve the problem.

**Comment by comejv** [comment] 2024-02-23 15:45
Ok that's weird, using the generated script worked...
![image](https://github.com/arnobpl/SymlinkCreator/assets/44554692/7b138fc1-a7ff-4a22-ab90-8eca7279e391)

But the app still doesn't. Any idea why ?

**Comment by arnobpl** [comment] 2024-02-23 16:11
Thank you for helping me to resolve the Symlink Creator issue. Since the generated script executed successfully, my guess is now: Symlink Creator could not run the script by itself due to file path length limit while executing the script by a wrapper script ([reference](https://github.com/arnobpl/SymlinkCreator/blob/c66f7fae1cfd512ffe1d1d00a11bdd2e14fdaed7/SymlinkCreator/core/ScriptExecutor.cs#L37)).

The solution to the problem is to disable file path length limit by following this Mircrosoft article: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

Could you follow the command (to disable file path length limit) mentioned in the Mircrosoft article and then try creating symlinks with Symlink Creator again?

Let me know the result.

Happy Symlinking!

**Comment by comejv** [comment] 2024-02-24 22:33
Tried, it, same non descriptive error ! But the generated script will be enough for my usage. Thank you for your answers.

**Comment by arnobpl** [comment] 2024-02-25 00:07
Glad to know that the generated script is working fine. But I don't know why it does not work directly with Symlink Creator itself, even no descriptive error message even after update. So the error occurred somewhere else. Anyway, I am closing this issue since there is no action item for me now.

Happy Symlinking!

**Comment by singularity2000** [comment] 2024-09-05 01:46
> 遇到了同样的报错，非常奇怪，当我在压缩包里直接运行程序则不会报错，解压后运行反而会报错。版本1.2.5 1.2.6 1.2.7 都存在相同问题 @comejv @arnobpl

你解压后用于存放SymlinkCreator的文件夹路径里有中文，我移动到纯英文目录就解决了

**Comment by arnobpl** [comment] 2024-09-05 02:01
@singularity2000 I was not able to reproduce the issue with Unicode characters. I tried both Chinese and Bengali characters. Let me know how to reproduce the issue so that I can fix it. Thank you!

Happy Symlinking!

<img width="529" alt="image" src="https://github.com/user-attachments/assets/381c7ae2-7c6c-4199-9950-b809ab38be03">

**Comment by maomaochong199** [comment] 2024-09-12 14:01
> > 遇到了同样的报错，非常奇怪，当我在压缩包里直接运行程序则不会报错，解压后运行反而会报错。版本1.2.5 1.2.6 1.2.7 都存在相同问题 @comejv @arnobpl
> 
> 你解压后用于存放SymlinkCreator的文件夹路径里有中文，我移动到纯英文目录就解决了
完全正确，路径里有中文复现报错了，纯英文路径正常

**Comment by arnobpl** [comment] 2024-09-12 15:48
Hello all, I was able to reproduce the issue! Thank you for the valuable feedback.

I will work on a fix and push an update.

Happy Symlinking!

**Closed** 2024-09-12 17:08 UTC
Labels: bug, help wanted
